export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_CATEGORIZED_PRODUCTS = "SET_CATEGORIZED_PRODUCTS";
export const SET_CATEGORIES_LIST = "SET_CATEGORIES_LIST";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";

export const SET_USERS = "SET_USERS";
export const SET_SELECTED_USER = "SET_SELECTED_USER";

export const IS_LOADING = "IS_LOADING";
export const IS_LOGGED = "IS_LOGGED";
